---
python_version: "3.12"
nodejs_version: "24.14.0"
golang_version: "1.26"
java_version: "21"

mise_pipx_packages:
  - aws-mfa
mise_npm_packages: []
mise_go_packages:
  - github.com/gohugoio/hugo@latest