---
- name: Get actual user home directory
  shell: "echo ${SUDO_USER:-$USER} | xargs -I {} getent passwd {} | cut -d: -f6"
  register: user_home_output
  changed_when: false

- name: Get actual username
  shell: "echo ${SUDO_USER:-$USER}"
  register: user_name_output
  changed_when: false

- name: Set user home directory fact
  set_fact:
    target_user_home: "{{ user_home_output.stdout }}"
    target_user: "{{ user_name_output.stdout }}"

- name: Install Go packages
  shell: "export PATH=\"{{ target_user_home }}/.local/go/go/bin:$HOME/go/bin:$PATH\" && CGO_ENABLED=1 go install github.com/gohugoio/hugo@latest"
  become_user: "{{ target_user }}"
  changed_when: false

- name: Install pipx packages
  shell: "export PATH=\"{{ target_user_home }}/.local/bin:$PATH\" && pipx install {{ item }}"
  become_user: "{{ target_user }}"
  changed_when: false
  loop:
    - aws-mfa

