---
- name: Create system fonts directory
  file:
    path: /usr/share/fonts
    state: directory
    mode: "0755"
  become: true

- name: Download Lilex archive
  get_url:
    url: https://github.com/mishamyrt/Lilex/releases/download/2.700/Lilex.zip
    dest: /tmp/Lilex.zip
    mode: "0644"
  become: true

- name: Extract Lilex
  unarchive:
    src: /tmp/Lilex.zip
    dest: /usr/share/fonts
    remote_src: yes
    creates: /usr/share/fonts/Lilex
  become: true

- name: Refresh font cache
  command: fc-cache -fv
  become: true
  changed_when: false
