# group_vars/local/all.yaml
os_codename: "trixie"
chezmoi_version: "2.69.4"

# Programming Languages
python_version: "3.12"
nodejs_version: "24.14.0"
golang_version: "1.26"
java_version: "21"

# DevOps Tools
k8s_version: "1.32"
helm_version: "3.16.4"
terraform_version: "1.14.6"
kubectx_version: "0.9.4"

# Mise Packages
mise_pipx_packages:
  - aws-mfa
mise_npm_packages: []
mise_go_packages:
  - github.com/gohugoio/hugo@latest
