---
- name: Baseline Software Installation
  hosts: local
  become: yes
  roles:
    - miseInstallation
    - utilityInstallation
    - applicationsInstallation
    - languageInstallation
    - devopsCliInstallation
    - dockerInstallation
