---
- name: Baseline Software Installation
  hosts: local
  become: yes
  roles:
    - utilityInstallation
    - applicationsInstallation
    - pythonInstallation
    - nodejsInstallation
    - goInstallation
    - javaInstallation
    - dockerInstallation
    - helmInstallation
    - awscliInstallation
    - terraformInstallation
    - kubectxInstallation
    - pipGoPackagesInstallation
