---
- name: Baseline Software Removal
  hosts: local
  become: yes
  roles:
    - role: misePackagesInstallation
      tags: never
      vars:
        removal_mode: true

- name: Remove utility applications
  hosts: local
  become: yes
  roles:
    - utilityInstallation

- name: Remove applications
  hosts: local
  become: yes
  roles:
    - applicationsInstallation

- name: Remove programming languages and tools
  hosts: local
  become: yes
  roles:
    - goInstallation
    - javaInstallation
    - nodejsInstallation
    - pythonInstallation
    - miseInstallation

- name: Remove DevOps tools
  hosts: local
  become: yes
  roles:
    - dockerInstallation
    - helmInstallation
    - awscliInstallation
    - terraformInstallation
    - kubectxInstallation