---
- name: Download Chezmoi .deb package
  ansible.builtin.get_url:
    url: https://github.com/twpayne/chezmoi/releases/download/v{{ chezmoi_version }}/chezmoi_{{ chezmoi_version }}_linux_amd64.deb
    dest: /tmp/chezmoi.deb
  become: yes

- name: Install Chezmoi from .deb using apt
  ansible.builtin.apt:
    deb: /tmp/chezmoi.deb
    state: present
  become: yes

- name: Update apt package cache
  ansible.builtin.apt:
    update_cache: yes
  become: yes

- name: Install utility packages
  ansible.builtin.apt:
    name:
      - wget
      - starship
      - tmux
      - tree
    state: present
  become: yes

- name: Clean apt cache
  ansible.builtin.apt:
    autoclean: yes
  become: yes
