---
- name: Install prerequisites for apt
  ansible.builtin.apt:
    name:
      - curl
      - gpg
    state: present
    update_cache: yes
  become: true

- name: Add Mise GPG key
  ansible.builtin.get_url:
    url: https://mise.jdx.dev/gpg-key.pub
    dest: /etc/apt/keyrings/mise-archive-keyring.asc
    mode: "0644"
  become: true

- name: Add Mise repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/mise-archive-keyring.asc] https://mise.jdx.dev/deb stable main"
    state: present
  become: true

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
  become: true

- name: Install mise
  ansible.builtin.apt:
    name: mise
    state: present
  become: true

- name: Download chezmoi .deb package
  ansible.builtin.get_url:
    url: "https://github.com/twpayne/chezmoi/releases/download/v{{ chezmoi_version }}/chezmoi_{{ chezmoi_version }}_linux_amd64.deb"
    dest: /tmp/chezmoi.deb
  become: true

- name: Install chezmoi from .deb
  ansible.builtin.apt:
    deb: /tmp/chezmoi.deb
    state: present
  become: true

- name: Install utility packages
  ansible.builtin.apt:
    name:
      - wget
      - tmux
      - tree
      - fd-find
      - jq
    state: present
  become: true

- name: Clean apt cache
  ansible.builtin.apt:
    autoclean: yes
  become: true
